image: node:latest

####### Global var
variables:
  NODE_ENV: "production"
  ALLOW_CORS: "true"
  MONGO_URI: "mongodb+srv://atlasMongoDBadmin:atlasMongoDBadmin@vigocluster-fywki:mongodb:net/VigoDB?retryWrites=true&w=majority"
  SECRET_OR_KEY: "random very very secret string"
  JWT_EXPIRES: "60"

stages:
  - production

production:
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY --skip_cleanup
  only:
    - master