language: node_js
node_js:
  - "stable"
install:
  - npm install newman
before_script:
  - node --version
  - npm --version
  - newman --version
cache:
  directories:
  - node_modules
script:
  - npm run eslint
  - npm run ci
